<?php

/**
 * @file
 */

function rooms_airbnb_rooms_channel_source() {
  $info = array();
  $info['AirBnB'] = array(
    'name' => 'AirBnB source',
    'description' => 'Imports AirBnB availability feeds.',
    'handler' => array(
      'parent' => 'iCalEventImporter',
      'class' => '\Drupal\rooms_airbnb\Import\AirBnbEventImporter',
      'path' => drupal_get_path('module', 'rooms_airbnb'),
      'module' => 'rooms_airbnb',
    ),
  );
  return $info;
}

function rooms_airbnb_rooms_channel_export() {
  $info = array();
  $info['AirBnB'] = array(
    'name' => 'AirBnB export',
    'description' => 'Exports availability to AirBnB.',
    'handler' => array(
      'parent' => 'iCalEventExporter',
      'class' => '\Drupal\rooms_airbnb\Export\AirBnbEventExporter',
      'path' => drupal_get_path('module', 'rooms_airbnb'),
      'module' => 'rooms_airbnb',
    ),
  );
  return $info;
}
